---

# Provisions the elements needed to build the councilroom.com site.
#
# See the build() method in the fabfile.py at the top level of the
# source code repository for more explanation on how the application
# is built.

- name: Make sure the apt cache is fresh (less than one day old)
  apt: update_cache=yes cache_valid_time=86400

- name: Install the apt packages necessary to build the Deb package of councilroom
  apt: pkg=$item
  with_items:
    - build-essential
    - debhelper
    - devscripts
    - dh-make
    - gnupg
    - libopenblas-base
    - libopenblas-dev
    - lintian
    - python-dev
    - python-pip
    - python-virtualenv

- name: Install the build-deps needed to install Python packages containing native code
  command: apt-get -qq build-dep $item
  with_items:
    - python-mongoengine
    - python-numpy
    - python-redis
    - python-scipy

# TODO: This should likly be removed since it is handled in the fab file
- name: Create the deployment directory and give it appropriate permissions
  file: path=/srv/councilroom state=directory owner=cr_prod group=cr_prod mode=0755
