---

# Playbook for provisioning the packages and code needed to run
# councilroom.com

- name: Make sure the apt cache is fresh (less than one day old)
  apt: update_cache=yes cache_valid_time=86400

- name: Create the production user
  user: name=cr_prod state=present

- include: redis-config.yml

# Configure MongoDB

- name: Install the apt packages necessary for MongoDB
  apt: pkg=$item
  with_items:
    - mongodb-server

- name: Configure the service directory for Mongo
  # This is kept in /srv so that it is easier to back with a EBS
  # volume when running on EC2.
  file: path=/srv/mongodb state=directory owner=root group=root mode=0755

- name: Mongo database dir
  file: path=/srv/mongodb/mongodb state=directory owner=mongodb group=mongodb mode=0755

- name: Deploy our MongoDB configuration file
  copy: src=mongodb.conf dest=/etc/mongodb.conf owner=root group=root mode=0644
  notify:
    - restart mongodb

# Configure Nginx

- name: Install the apt packages needed by Nginx
  apt: pkg=$item
  with_items:
    - nginx-full
