---

# Playbook for provisioning the packages and code needed to run
# councilroom.com

- name: Make sure the apt cache is fresh (less than one day old)
  apt: update_cache=yes cache_valid_time=86400

- name: Create the production user
  user: name=cr_prod state=present

- include: redis-config.yml


# Configure MongoDB

- name: Install the apt packages necessary for MongoDB
  apt: pkg=$item
  with_items:
    - mongodb-server

- name: Configure the service directory for Mongo
  # This is kept in /srv so that it is easier to back with a EBS
  # volume when running on EC2.
  file: path=/srv/mongodb state=directory owner=root group=root mode=0755

- name: Mongo database dir
  file: path=/srv/mongodb/mongodb state=directory owner=mongodb group=mongodb mode=0755

- name: Deploy our MongoDB configuration file
  copy: src=mongodb.conf dest=/etc/mongodb.conf owner=root group=root mode=0644
  notify:
    - restart mongodb


# Configure Circus

- name: Install the Circus config file
  copy: src=circus/circus.ini dest=/srv/councilroom/circus.ini owner=root group=root mode=0644

- name: Install Circus as a service
  copy: src=circus/councilroom.conf dest=/etc/init/councilroom.conf owner=root group=root mode=0644
  notify:
    - restart councilroom

- name: Enable the Councilroom/circus service
  service: name=councilroom enabled=yes


# Configure Nginx

- name: Install the apt packages needed by Nginx
  apt: pkg=$item
  with_items:
    - nginx-full

- name: Deploy our Nginx configuration file
  copy: src=nginx/councilroom-prod.conf dest=/etc/nginx/sites-available owner=root group=root mode=0644

- name: Make log directory used by Nginx
  file: path=/srv/councilroom/logs state=directory owner=root group=root mode=0755

- name: Disable the default Nginx site
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify:
    - restart nginx

- name: Enable the Councilroom site in Nginx
  file: src=/etc/nginx/sites-available/councilroom-prod.conf dest=/etc/nginx/sites-enabled/councilroom.com state=link 
  notify:
    - restart nginx

- name: Make sure nginx is left running
  service: name=nginx enabled=yes state=started
